openapi: 3.0.1
info:
  description: SFC-IVR-apis
  title: SFC-IVR
  version: 1.0.0
servers:
- url: //62.72.57.205:8098/
tags:
- description: Admin Controller
  name: admin-controller
- description: OTP Controller
  name: otp-controller
- description: SP Controller
  name: sp-controller
- description: User Controller
  name: user-controller
paths:
  /SP/verifyOTP:
    post:
      operationId: verifyOTPUsingPOST
      parameters:
      - description: email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: otp
        in: query
        name: otp
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: verifyOTP
      tags:
      - otp-controller
      x-accepts:
      - '*/*'
  /addSpPositionData:
    post:
      operationId: addSpPositionDataUsingPOST
      parameters:
      - description: position
        in: query
        name: position
        schema:
          type: string
      - description: spId
        in: query
        name: spId
        required: true
        schema:
          type: string
      - description: text
        in: query
        name: text
        schema:
          type: string
      - description: type
        in: query
        name: type
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              format: binary
              type: string
        description: file
        required: false
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: addSpPositionData
      tags:
      - sp-controller
      x-codegen-request-body-name: file
      x-content-type: multipart/form-data
      x-accepts:
      - '*/*'
  /admin/signin:
    post:
      operationId: signinUsingPOST
      parameters:
      - description: email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: query
        name: password
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SigninResponse'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: signin
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /admin/signup:
    post:
      operationId: signupUsingPOST
      parameters:
      - description: email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: name
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: password
        in: query
        name: password
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: signup
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /createServiceProvider:
    post:
      operationId: createServiceProviderUsingPOST
      parameters:
      - description: address
        in: query
        name: address
        schema:
          type: string
      - description: email
        in: query
        name: email
        schema:
          type: string
      - description: invokingNumbers
        explode: true
        in: query
        name: invokingNumbers
        schema:
          items:
            format: int32
            type: integer
          type: array
        style: form
      - description: name
        in: query
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: createServiceProvider
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /downloadfile/{fileName}:
    get:
      operationId: downloadfileUsingGET
      parameters:
      - description: fileName
        in: path
        name: fileName
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resource'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: downloadfile
      tags:
      - sp-controller
      x-accepts:
      - '*/*'
  /generateOTPForSignup/{email}:
    get:
      operationId: generateOTPForSignupUsingGET
      parameters:
      - description: email
        in: path
        name: email
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: generateOTPForSignup
      tags:
      - otp-controller
      x-accepts:
      - '*/*'
  /getAllServiceProviders:
    get:
      operationId: getAllServiceProvidersUsingGET
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: getAllServiceProviders
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /getAllUsers:
    get:
      operationId: getAllUsersUsingGET
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: getAllUsers
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /getSpPositionData/{spId}:
    get:
      operationId: getSpPositionDataUsingGET
      parameters:
      - description: spId
        in: path
        name: spId
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: getSpPositionData
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /getUsers/{spId}:
    get:
      operationId: getUsersUsingGET
      parameters:
      - description: spId
        in: path
        name: spId
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: getUsers
      tags:
      - sp-controller
      x-accepts:
      - '*/*'
  /getserviceProviderInfo/{uniqueId}:
    get:
      operationId: getserviceProviderInfoUsingGET
      parameters:
      - description: uniqueId
        in: path
        name: uniqueId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: getserviceProviderInfo
      tags:
      - admin-controller
      x-accepts:
      - '*/*'
  /logout/{spId}:
    get:
      operationId: logoutUsingGET
      parameters:
      - description: spId
        in: path
        name: spId
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: logout
      tags:
      - sp-controller
      x-accepts:
      - '*/*'
  /resetPassword:
    post:
      operationId: resetPasswordUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceProvider'
        description: serviceProvider
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: resetPassword
      tags:
      - sp-controller
      x-codegen-request-body-name: serviceProvider
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /signin:
    post:
      operationId: signinUsingPOST_1
      parameters:
      - description: email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: password
        in: query
        name: password
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SigninResponse'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: signin
      tags:
      - sp-controller
      x-accepts:
      - '*/*'
  /sp/generateOTPForResetPassword/{email}:
    get:
      operationId: generateOTPForResetPasswordUsingGET
      parameters:
      - description: email
        in: path
        name: email
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: generateOTPForResetPassword
      tags:
      - otp-controller
      x-accepts:
      - '*/*'
  /user/editProfile:
    put:
      operationId: editProfileUsingPUT
      parameters:
      - description: name
        in: query
        name: name
        schema:
          type: string
      - description: spId
        in: query
        name: spId
        schema:
          type: string
      - description: userId
        in: query
        name: userId
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: editProfile
      tags:
      - user-controller
      x-accepts:
      - '*/*'
  /user/signin:
    post:
      operationId: signinUsingPOST_2
      parameters:
      - description: phoneNumber
        in: query
        name: phoneNumber
        schema:
          type: string
      - description: spId
        in: query
        name: spId
        schema:
          type: string
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SigninResponse'
          description: OK
        "201":
          content: {}
          description: Created
        "401":
          content: {}
          description: Unauthorized
        "403":
          content: {}
          description: Forbidden
        "404":
          content: {}
          description: Not Found
      summary: signin
      tags:
      - user-controller
      x-accepts:
      - '*/*'
components:
  schemas:
    InputStream:
      title: InputStream
      type: object
    Resource:
      example:
        readable: true
        file: ""
        filename: filename
        description: description
        inputStream: "{}"
        uri: https://openapi-generator.tech
        open: true
        url: http://example.com/aeiou
      properties:
        description:
          type: string
        file:
          format: binary
          type: file
        filename:
          type: string
        inputStream:
          title: InputStream
          type: object
        open:
          type: boolean
        readable:
          type: boolean
        uri:
          format: uri
          type: string
        url:
          format: url
          type: string
      title: Resource
      type: object
    Response:
      example:
        result: "{}"
        code: 0
        error: error
        message: message
      properties:
        code:
          format: int32
          type: integer
        error:
          type: string
        message:
          type: string
        result:
          properties: {}
          type: object
      title: Response
      type: object
    ServiceProvider:
      example:
        password: password
        address: address
        creationTime: 0
        initialPassword: initialPassword
        modificationTime: 1
        name: name
        active: active
        isLoggedIn: isLoggedIn
        id: 6
        email: email
        isEmailVerified: isEmailVerified
        uniqueId: uniqueId
      properties:
        active:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        address:
          type: string
        creationTime:
          format: int64
          type: integer
        email:
          type: string
        id:
          format: int32
          type: integer
        initialPassword:
          type: string
        isEmailVerified:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        isLoggedIn:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        modificationTime:
          format: int64
          type: integer
        name:
          type: string
        password:
          type: string
        uniqueId:
          type: string
      title: ServiceProvider
      type: object
    SigninResponse:
      example:
        result: "{}"
        code: 0
        error: error
        message: message
        token: token
      properties:
        code:
          format: int32
          type: integer
        error:
          type: string
        message:
          type: string
        result:
          properties: {}
          type: object
        token:
          type: string
      title: SigninResponse
      type: object
x-original-swagger-version: "2.0"

